version: "3.4"

services:
  postgres:
    image: postgres:11
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres:/postgres/data:rw
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - network


volumes:
  postgres:

networks:
  network:
    driver: bridge
